#!/usr/bin/env bash
set -euo pipefail

required_vars=(
  MINIO_ROOT_USER
  MINIO_ROOT_PASSWORD
  AIRFLOW_DB_USER
  AIRFLOW_DB_PASSWORD
  AIRFLOW_FERNET_KEY
  AIRFLOW_SECRET_KEY
  AIRFLOW_ADMIN_USER
  AIRFLOW_ADMIN_PASSWORD
  ANALYTICS_DB_USER
  ANALYTICS_DB_PASSWORD
  METABASE_DB_USER
  METABASE_DB_PASSWORD
)

for var_name in "${required_vars[@]}"; do
  if [ -z "${!var_name:-}" ]; then
    echo "Missing required environment variable: ${var_name}" >&2
    exit 1
  fi
done

cat > .env <<EOF
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_ENDPOINT=minio:9000
AIRFLOW_DB_USER=${AIRFLOW_DB_USER}
AIRFLOW_DB_PASSWORD=${AIRFLOW_DB_PASSWORD}
AIRFLOW_DB_NAME=airflow
AIRFLOW_FERNET_KEY=${AIRFLOW_FERNET_KEY}
AIRFLOW_SECRET_KEY=${AIRFLOW_SECRET_KEY}
AIRFLOW_ADMIN_USER=${AIRFLOW_ADMIN_USER}
AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
ANALYTICS_DB_HOST=analytics-db
ANALYTICS_DB_PORT=5432
ANALYTICS_DB_NAME=analytics
ANALYTICS_DB_USER=${ANALYTICS_DB_USER}
ANALYTICS_DB_PASSWORD=${ANALYTICS_DB_PASSWORD}
METABASE_DB_HOST=metabase-db
METABASE_DB_PORT=5432
METABASE_DB_NAME=metabase
METABASE_DB_USER=${METABASE_DB_USER}
METABASE_DB_PASSWORD=${METABASE_DB_PASSWORD}
EOF

echo ".env written - verifying (keys only):"
cut -d= -f1 .env
