name: CI - Lint

on:
  push:
    paths:
      - "airflow/dags/**"
      - "data-generator/**"
      - "tests/**"
  pull_request:
    paths:
      - "airflow/dags/**"
      - "data-generator/**"
      - "tests/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install tools
        run: pip install flake8 black isort mypy

      - name: Run flake8
        run: flake8 airflow/dags/ data-generator/ tests/

      - name: Check formatting
        run: black --check airflow/dags/ data-generator/ tests/

      - name: Check imports
        run: isort --check-only airflow/dags/ data-generator/ tests/